name: Konsarpoo tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
        fail-fast: false
        matrix:
          operating-system: [ ubuntu-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies with dotnet
      run: dotnet restore
    # For cross-platform compatibility, we'll use dotnet CLI instead of nuget.exe on non-Windows platforms
    - name: Setup NuGet.exe for use with actions (Windows only)
      if: ${{ runner.os == 'Windows' }}
      uses: NuGet/setup-nuget@v1.2.0
    - name: Restore with NuGet (Windows only)
      if: ${{ runner.os == 'Windows' }}
      run: nuget restore Konsarpoo.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --configuration Release --no-restore --logger "trx;LogFileName=test-results-${{ matrix.operating-system }}.trx"
    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.operating-system }}
        path: ~/work/Konsarpoo/Konsarpoo/Konsarpoo.Tests/TestResults