name: Konsarpoo tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
        fail-fast: false
        matrix:
          operating-system: [ ubuntu-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0
    - run: nuget restore Konsarpoo.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --configuration Release --no-restore --logger "trx;LogFileName=test-results-${{ matrix.operating-system }}.trx"
    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ~/work/Konsarpoo/Konsarpoo/Konsarpoo.Tests/TestResults